#!/usr/bin/perl
## Pombert Lab, 2018
my $name = 'parse_hmmtbl.pl';
my $version = '0.2a';
my $updated = '12/03/2021';

use strict; use warnings; use Getopt::Long qw (GetOptions);

my $usage = <<"OPTIONS";
NAME		${name}
VERSION		${version}
UPDATED		${updated}
SYNOPSIS	Parses the output of hmmsearch into a concise, tab-delimited format

USAGE		${name} -tbl *.hmm.*.tbl -out hmmtable.tsv

OPTIONS:
-t (--tbl)	TBL files generated by run_hmmsearch.pl
-o (--out)	Output table name [Default = hmmtable.tsv]
OPTIONS
die "\n$usage\n" unless @ARGV;

## Defining GetOptions() variables
my @tbl;
my $table = 'hmmtable.tsv';
GetOptions(
	't|tbl=s@{1,}' => \@tbl,
	'o|out=s' => \$table
);

## Print table header
open OUT, ">", "$table" or die "Can't create file $table: $!\n";
print OUT "Query\tTarget\tE-value\tProduct\tGenus\tSpecies\tOS descriptor\n";

## Parsing files
while (my $file = shift@tbl){
	open IN, "<", "$file" or die "Can't read file $file: $!\n";
		while (my $line = <IN>){
		chomp $line;
		if ($line =~ /^#/){ next;} ## Skipping comments 
		## File format is space separated, must use a regex...
		elsif ($line =~ /^(\S+)\s+-\s+(\S+)\s+-\s+(\S+e-\d+)(?:\s+\S+){6}\s+(?:\d+\s+){7}(.*)\sOS=(.*?)(?:OX|GN|PE|SV)=/){
			my $target = $1;
			my $query = $2;
			my $evalue = $3;
			my $product = $4;
			my $OS = $5;
			my ($species,$genus) = $OS =~ /^((\S+)\s+\S+)/;
			print OUT "$query\t$target\t$evalue\t$product\t$genus\t$species\t$OS\n";
		}
	}
}
